# Matrix Algebra
import numpy as np

A = np.array([(1,2,3), (2,7,4)])
#print(A)
print('A shape=',A.shape)
B = np.array([(1,-1),(0,1)])
#print(B)
print('B shape=',B.shape)
C = np.array([(5,-1),(9,1),(6,0)])
#print(C)
print('C shape=',C.shape)
D = np.array([(3,-2,-1),(1,2,3)])
#print(D)
print('D shape=',D.shape)
u = np.array([(6,2,-3,5)])
#print(u)
print('u shape=',u.shape)
v = np.array([(3,5,-1,4)])
#print(v)
print('v shape=',v.shape)
w = np.array([(1),(8),(0),(5)])
#print(w)
print('w shape=',w.shape)

print("#"*20)
print("# Vector Operations")
#vector operations
print('u+v=',u+v)
print('u-v=',u-v)
print('@u=',6 * u)
print('u dot v=',np.vdot(u,v))
print('norm(u)=',np.linalg.norm(u))
print("#"*20)

print("#"*20)
print("# Matrix Operations")
#print('A + C =',A+C) # not defined
print('A - C transpose=')
print(A - np.transpose(C))
print('C transpose + 3D=')
print(np.transpose(C) + 3*D)
print('BA=')
print(np.dot(B,A))
print('BA transpose=')
#print(np.dot(B,np.transpose(A))) #undefined
print("#"*20)
print('BC= undefined')
#print(np.dot(B,C)) #undefined
print('CB=')
print(C.dot(B))
print('B4=')
print(B**4)
print('A*Atran=')
print(A.dot(np.transpose(A)))
print('D*Dtran=')
print((D.transpose()).dot(D))
print("#"*20)
